# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-01 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry', models.DateField()),
                ('job_category', models.CharField(blank=True, choices=[('TECHNICIAN', 'Technician'), ('CHEMIST', 'Chemist')], max_length=255, null=True)),
                ('education', models.CharField(blank=True, choices=[('HS', 'High School/GRE'), ('BA/BS', 'Bachelor of Art and Science'), ('MA/MS', 'Master of Art and Science'), ('PHD', 'Doctor of Philosophy')], max_length=255, null=True)),
                ('experience', models.CharField(blank=True, max_length=255, null=True)),
                ('skills', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('benefits', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
