# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-27 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(help_text='Describe the position and the working conditions.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='expiry',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='headline',
            field=models.CharField(blank=True, help_text='A concise high-level overview of the job.', max_length=255, null=True),
        ),
    ]
