# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-28 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20191227_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_frequency',
            field=models.CharField(choices=[('HR', 'Per-Hour'), ('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONTH', 'Monthly'), ('YEAR', 'Yearly')], default='YEAR', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=15),
            preserve_default=False,
        ),
    ]
