# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-28 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20191227_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(decimal_places=2, help_text='Two decimal places. Ex. 65,200.23', max_digits=15),
        ),
    ]
