# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-28 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('jobs', '0009_auto_20191228_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country', verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City', verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Region', verbose_name='region'),
            preserve_default=False,
        ),
    ]
