# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-28 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20191228_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.CharField(max_length=255),
        ),
    ]
