# Generated by Django 2.2 on 2019-12-31 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20191228_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.City', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='job',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cities_light.Region', verbose_name='region'),
        ),
    ]
