# Generated by Django 2.2 on 2020-01-07 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('jobs', '0013_auto_20191230_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='city',
        ),
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='state',
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cities_light.City', verbose_name='location'),
            preserve_default=False,
        ),
    ]
