# Generated by Django 2.2 on 2020-01-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20200107_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Two decimal places. Ex. 65,200.23', max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary_frequency',
            field=models.CharField(blank=True, choices=[('HR', 'Per-Hour'), ('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONTH', 'Monthly'), ('YEAR', 'Yearly')], max_length=225, null=True),
        ),
    ]
