# Generated by Django 2.2.5 on 2020-01-16 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20200115_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_frequency',
            field=models.CharField(blank=True, choices=[('HR', 'Per-Hour'), ('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONTH', 'Monthly'), ('YEAR', 'Yearly')], max_length=225, null=True),
        ),
    ]
