# Generated by Django 2.2.5 on 2020-01-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='height_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='width_field',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
