# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-01 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='is_employeer',
            new_name='is_employer',
        ),
    ]
