# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-01 02:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$', 'Only alphanumeric and underscores')]),
        ),
    ]
