# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-01 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191130_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='is_candidate',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='is_employer',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='account_type',
            field=models.CharField(choices=[('CANDIDATE', 'Candidate'), ('EMPLOYEER', 'Employeer')], default='Candidate', max_length=255),
            preserve_default=False,
        ),
    ]
