# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-01 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191130_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='education',
            field=models.CharField(blank=True, choices=[('HS', 'High School/GRE'), ('BA/BS', 'Bachelor of Art and Science'), ('MA/MS', 'Master of Art and Science'), ('PHD', 'Doctor of Philosophy')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='speciality',
            field=models.CharField(blank=True, choices=[('SYNTHESIS', 'Cannabinoid Synthesis'), ('EXTRACTION', 'Cannabinoid/Terpene Extraction'), ('POSTPROCESS', 'Winterization/Solvent Recovery'), ('DISTILLATION', 'Cannabinoid Distillation'), ('ANALYTICS', 'Cannabinoid Analytics'), ('ISOLATIONS', 'Flash Chromatography/Crystallization')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='account_type',
            field=models.CharField(choices=[('CANDIDATE', 'Candidate'), ('EMPLOYER', 'Employer')], max_length=255),
        ),
    ]
