# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-27 01:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191201_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_url', models.URLField()),
                ('regulatory_id', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='education',
            field=models.CharField(blank=True, choices=[('HS', 'High School/GRE'), ('BA/BS', 'Bachelor of Art/Science'), ('MA/MS', 'Master of Art/Science'), ('PHD', 'Doctor of Philosophy')], max_length=255, null=True),
        ),
    ]
