# Generated by Django 2.2.9 on 2020-02-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200205_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-end_year']},
        ),
        migrations.AddField(
            model_name='siteuser',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
