# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-28 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191226_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='account_type',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='education',
            field=models.CharField(blank=True, choices=[('HS', 'High School/GRE'), ('BA/BS', 'Bachelor of Art/Science'), ('MA/MS', 'Master of Art/Science'), ('PHD', 'Doctor of Philosophy')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='is_business',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='CandidateProfile',
        ),
        migrations.DeleteModel(
            name='EmployerProfile',
        ),
    ]
