# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-28 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20191227_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='headline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
