# Generated by Django 2.2.9 on 2020-02-13 21:23

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200206_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='is_available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Separate tags by commas.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
