# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-28 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_siteuser_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='slug',
            field=models.SlugField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
