# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-28 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_siteuser_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='education',
            field=models.CharField(blank=True, choices=[('HS', 'High School/GRE'), ('AS', "Associate's"), ('BA/BS', "Bachelor's"), ('MA/MS', "Master's"), ('PHD', 'Doctorate')], max_length=255, null=True),
        ),
    ]
