# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-29 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20191228_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.Region', verbose_name='region'),
        ),
    ]
