# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-12-30 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20191229_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cities_light.City', verbose_name='city'),
        ),
    ]
