# Generated by Django 2.2 on 2019-12-31 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191229_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.City', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.City', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.Region', verbose_name='region'),
        ),
    ]
