# Generated by Django 2.2 on 2019-12-31 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('cities_light', '0008_city_timezone'),
        ('accounts', '0014_auto_20191230_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='state',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cities_light.City', verbose_name='location'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
